// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPcH_DxerXT-2S6zpINnTv0SMnnZ8qT0',
    appId: '1:393167181575:web:e9d38c5704b8349f9c57a2',
    messagingSenderId: '393167181575',
    projectId: 'catime-ccd4f',
    authDomain: 'catime-ccd4f.firebaseapp.com',
    storageBucket: 'catime-ccd4f.appspot.com',
    measurementId: 'G-4BXS2RLW7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtgpjPzcGY8-FiNOhMnxF7CTrul7uG3zw',
    appId: '1:393167181575:android:2330009ff6dee84f9c57a2',
    messagingSenderId: '393167181575',
    projectId: 'catime-ccd4f',
    storageBucket: 'catime-ccd4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB08UfiSMX_bwLLxvgkVUGqBX8KSNO8wtI',
    appId: '1:393167181575:ios:795a74f1172cf83e9c57a2',
    messagingSenderId: '393167181575',
    projectId: 'catime-ccd4f',
    storageBucket: 'catime-ccd4f.appspot.com',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB08UfiSMX_bwLLxvgkVUGqBX8KSNO8wtI',
    appId: '1:393167181575:ios:795a74f1172cf83e9c57a2',
    messagingSenderId: '393167181575',
    projectId: 'catime-ccd4f',
    storageBucket: 'catime-ccd4f.appspot.com',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPcH_DxerXT-2S6zpINnTv0SMnnZ8qT0',
    appId: '1:393167181575:web:1ea2c5db95f6a47f9c57a2',
    messagingSenderId: '393167181575',
    projectId: 'catime-ccd4f',
    authDomain: 'catime-ccd4f.firebaseapp.com',
    storageBucket: 'catime-ccd4f.appspot.com',
    measurementId: 'G-W39L3LVSFE',
  );
}
